-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 18, 2019 at 04:59 AM
-- Server version: 10.4.8-MariaDB
-- PHP Version: 7.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `teamnd`
--

-- --------------------------------------------------------

--
-- Table structure for table `fruit`
--

CREATE TABLE `fruit` (
  `fruit_id` int(11) NOT NULL,
  `fruit_code` varchar(20) NOT NULL,
  `fruit_name` varchar(50) NOT NULL,
  `fruit_country` varchar(50) NOT NULL,
  `fruit_status` int(11) NOT NULL,
  `fruit_category` varchar(50) NOT NULL,
  `fruit_cost` int(11) NOT NULL,
  `fruit_sale` int(11) NOT NULL,
  `fruit_describe` text NOT NULL,
  `fruit_image` text NOT NULL,
  `fruit_date` year(4) NOT NULL,
  `fruit_expiryDate` year(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `fruit`
--

INSERT INTO `fruit` (`fruit_id`, `fruit_code`, `fruit_name`, `fruit_country`, `fruit_status`, `fruit_category`, `fruit_cost`, `fruit_sale`, `fruit_describe`, `fruit_image`, `fruit_date`, `fruit_expiryDate`) VALUES
(5, 'ND1', 'Nho Đen Midnnight', 'Úc', 50, 'Nho', 200000, 0, '<strong>1. Giới thiệu nho đen không hạt Úc </strong>\r\nVới khí hậu ôn đới, ngày nóng đêm lạnh, đất tốt của các vùng thung lũng ở Australia đã tạo môi trường tuyệt vời để cây nho Úc phát triển và cho sản lượng cùng chất lượng tốt nhất. Khu vực trồng nhiều nho nhất là: Sunraysia và thung lũng Murray gần sông Murray tại Victoria; Riverina ở New South Wales; và đông nam Queensland, Carnarvon, thung lũng Swan và Tây Nam của Tây Úc, trung tâm New South Wales, Riverland ở Nam Úc và Lãnh thổ phía Bắc trung tâm.Người trồng được đào tạo kiến thức vững chắc, thường xuyên kiểm tra vườn nho trong suốt quá trình trồng và thu hoạch, đảm bảo đủ nước tưới, kiểm soát bất kì loại sâu bệnh nào có trong vườn,… Nên nho đen Úc luôn đồng đều về màu sắc, kích thước, quả ngọt ngon được nhiều thị trường khó tính trên thế giới yêu thích\r\nSau thời gian thu hoạch nếu vận chuyển bằng đường hàng không chỉ mất 40 – 60 giờ để về đến Việt Nam, nếu vận chuyển bằng đường biển, bảo quản trong kho lạnh thì mất 12 – 20 ngày sẽ cập cảng\r\n\r\n\r\n<img src=\"/fruits/content/nhoden1uc.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm</strong>\r\nLà một trong những trái cây Úc có lượng tiêu thụ rất lớn, nho đen không hạt với hình dáng thuôn như hình bóng bầu dục, quả to và cứng quả. Bên ngoài có một lớp phấn mỏng tự nhiên để bảo vệ quả, thịt giòn chắc, nhiều nước và có vị ngọt thơm đậm\r\nĐặc trưng của dòng nho đen là phần vỏ hơi xin xít nên nhiều người ăn lần đầu không thích lắm, nhưng ăn đến lần thứ 2 bạn sẽ cảm nhận được vị ngọt đọng lại đầu lưỡi ngay sau cái vị chát rất đặc trưng đó.\r\n\r\n<strong>3. Giá trị dinh dưỡng</strong>\r\nNho đen không hạt Australia lợi ích sức khỏe cao hơn hẳn so với các dòng nho khác. Phần vỏ màu đen chứa rất nhiều chất chống oxy hóa flavonoid chống lão hóa và phòng ngừa các bệnh ung thư. Tăng khả năng miễn dịch của cơ thể\r\nTheo các nhà khoa học đây là “thuốc doping” tự nhiên  có tác dụng tập trung tinh thần, cải thiện lưu thông máu, khí huyết, ổn định huyết áp.\r\nCải thiện sức co bóp của cơ trơn đường tiêu hóa, thúc đẩy lưu thông các chất chứa trong đường tiêu hóa, ngừa táo bón, gia tăng sự xuất tiết các dịch tiêu hóa và rút ngắn quá trình lên men trong ruột,…', '/fruits/Nho/NHO ĐEN KHÔNG HẠT ÚC MIDNIGHT/ad.jpg', 2019, 2020),
(6, 'CU1', 'Cam Vàng Navel', 'Úc', 40, 'Cam', 96000, 0, '<strong>1.  Giới Thiệu cam Navel Úc</strong>\r\nCam Navel là loại trái cây đột biến, lần đầu tiên được phát hiện tại nhà vườn ở Brazil năm 1820. Sau đó, Navel bắt đầu được nhân rộng ra các nước khác trên thế giới như Mỹ , Bắc Phi, Địa Trung Hải và trong đó có Australia. Cam Navel Úc là một trong những loại cam phổ biến nhất hiện nay và được người tiêu dùng trên toàn thế giới yêu thích.\r\n\r\n\r\n<img src=\"/fruits/content/camneval1.jpg\">\r\n\r\n\r\n<strong>2.  Đặc điểm</strong>\r\nTrái cam to tròn, màu vàng tươi sáng và óng ả như ánh nắng mặt trời, phần vỏ mỏng thơm chứa nhiều tinh dầu tự nhiên. Khi bóc lớp vỏ vàng tươi ra, bạn sẽ thấy ở phần đáy (nơi mà hoa cam kết trái) có lớp vỏ thụt vào như một dạng quả nhỏ chưa phát triển, trông rất giống cái rốn chính vì thế nó được gọi là cam Navel\r\nMúi cam to, tép mọng nước màu vàng tươi, ít xơ, vị ngọt thanh, thơm mát và đặc trưng mà ai ai cũng thích là hầu hết không có hạt. Vị tươi ngọt sảng khoái tan vào trong miệng khiến bạn cảm thấy cực kì sung sướng khi được thưởng thức Navel Úc\r\n\r\n<strong>3.  Giá trị dinh dưỡng</strong>\r\nCũng giống như Navel Mỹ, Cara ruột đỏ, Navel Australia có một giá trị dinh dưỡng khổng lồ. Trung bình trong một quả chỉ có khoảng 60 calo nhưng có thể đáp ứng được 116% nhu cầu vitamin C, 13% chất xơ, 10% folate, 8% thiamin, 7% kali, 6% vitamin A, 5% Canxi cơ thể cần hàng ngày nên\r\n-   Hỗ trợ tiêu hóa, ngăn ngừa viêm loét dạ dày, trào ngược axit, phòng chống táo bón mãn tính\r\n-   Tăng cường thể lực, giải khát, điều hòa giấc ngủ\r\n-   Phòng chống ung thư, kháng viêm, tránh cảm cúm\r\n-   Giảm nguy cơ mắc cách bệnh về tim mạch và đặc biệt là chống lại quá trình lão hóa', '/fruits/Cam/Cam Vàng Navel Úc/camnevall.png', 2019, 2020),
(7, 'CU2', 'Cam Đỏ Cara', 'Úc', 60, 'Cam', 86000, 0, '<strong> 1.Giới thiệu chung </strong>\r\n  Cam vàng Cara ruột đỏ có nguồn gốc ở vùng Valencia và Venezuela, đến thời kỳ phục hưng, nhờ quá trình giao lưu văn hóa giữa các nước Châu Âu và Châu Á nên Cam du nhập đến các nước trên thế giới. Hầu hết cam vàng ruột đỏ cũng như họ hàng giống Quýt thích ưu khí hậu nhiệt đới và nóng. Hiện nay, Cam vàng ruột đỏ được trồng ở các quốc gia trên thế giới như Ai Cập, Nam Phi, Mỹ. Úc... kể cả Việt Nam cũng được trồng tại một số tỉnh phía Nam.\r\n\r\n\r\n<img src=\"/fruits/content/camcara1.jpg\">\r\n\r\n\r\n<strong> 2.Đặc điểm </strong>\r\n  Đặc điểm vỏ màu vàng, mỏng, rất mịn, dễ bóc, nhiều nước và đặc biệt không hạt, ngọt dịu pha ít chua nhẹ, mui thơm gần giống hương bưởi.\r\nCam được ăn tươi là phổ biến nhất hiện nay. Tuy nhiên, cam còn được chế biến nhiều món ăn như: salad, nấu trà, sinh tố, thạch cam.....\r\n\r\n<strong> 3.Giá trị dinh dưỡng </strong>\r\n  Hỗn hợp chất Lycopene và Carotenoid tạo tạo ra ruột đỏ nên Caritenoid rất tốt cho cơ thể, phù hợp với những người có chế độ ăn kiêng.\r\nChất Lycopene có tác dụng chống các loại ung thư tuyến tiền liệt, ung thư phổi,cổ tử cung và da. Ngoài ra, Lycopene còn là một chất chống oxi hóa nó có thể giúp chống lại bệnh thoái hóa như suy tim và tập trung vào việc diệt các mô ung thư trong cơ thể con người. Quả là một loại trái cây hữu hiệu không thưa kém gì việt quất.', '/fruits/Cam/Cam đỏ Cara Úc/camcara.jpg', 2019, 2020),
(8, 'BO1', 'Bơ Hass', 'Úc', 36, 'Bơ', 181000, 0, '<strong>1. Giới thiệu chung</strong>\r\nBơ Hass có nguồn gốc từ Nam Mỹ, được trồng nhiều ở Úc, Mỹ, New Zealand và nhiều nước trên thế giới, trong đó cây bơ Hass là giống bơ chủ chốt của Úc. \r\n\r\n\r\n<img src=\"/fruits/content/bohass1.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm </strong>\r\nQuả hình bầu dục dài hơn các giống bơ khác, có vỏ dày và cứng, vỏ màu xanh đậm,da sần sùi, khi chín vỏ có màu tím. Trọng lượng trung bình là 130-340gr, tỉ lệ thịt quả 70-75%, thịt quả có màu vàng kem, nhiều chất béo và có mùi thơm đặc trưng.\r\n\r\n<strong>3. Giá trị dinh dưỡng</strong>\r\nDo có nhiều lợi ích về dinh dưỡng bao gồm cả chất xơ,vitamin C,E,K, các chất kẽm , đồng, kali.... nên trái bơ đc Hiệp hội Tiểu đường tại Mỹ liệt kê vào danh sách như những \"siêu sao\" đứng đầu về dinh dưỡng.\r\nĐặc biệt trong bơ cũng rất giàu acid folic, nguồn dinh dưỡng quan trọng cho một trái tim khỏe.\r\nBơ còn chưa nguồn lutein cao, có tác dụng bảo vệ đôi mắt, ngăn ngừa các bệnh về mắt.', '/fruits/Bơ/Bơ Hass/bo.jpg', 2019, 2020),
(9, 'CU3', 'Quýt Úc', 'Úc', 123, 'Cam', 69000, 0, '<strong>1.  Giới thiệu</strong>\r\nQuýt Úc được trồng rộng rãi ở Nam Úc nơi mà khí hậu nhiệt đới và cận nhiệt đới ấm nóng. Tạo điều kiện thích hợp cho quýt úc phát triển đạt độ ngon ngọt nhất.\r\nBạn sẽ dễ dàng mua được quýt úc tại các cửa hàng hoa quả nhập khẩu từ tháng 4 đến tháng 10.\r\n\r\n\r\n<img src=\"/fruits/content/quytuc1.jpg\">\r\n\r\n\r\n<strong>2.  Đặc điểm</strong>\r\nQuýt úc có màu vàng ươm, các đốm tinh dầu to bóng, quả hơi dẹt. Thịt mọng nước, vị ngọt, có hạt. Hương vị tươi mới khiến bạn phát cuồng và không ngừng ăn chúng đấy.\r\nTrung bình khoảng 5 quả/kg. Màu sắc tươi sáng, hương vị hoàn hảo rất phù hợp để làm quà tặng, quà biếu cho những người thân yêu đấy.\r\n\r\n<strong>3.   Dinh dưỡng và sức khỏe</strong>\r\nVitamin C có trong quýt úc giúp bổ sung năng lượng cho các bà mẹ khi mới sinh\r\nQuýt chứa nhiều axit amin, đường hợp chất, chất béo, photpho, sắt..\r\nBạn vẫn có thể tận dụng được vỏ quýt bởi nó chứa nhiều vitamin D duy trì tính dẻo của huyết quản mao mạch, phòng chống mạch máu mỡ và thấm máu\r\nĐây là một loại hoa quả, thực phẩm ăn kiêng giàu chất xơ, vitamin A, B, canxi, Magnesium, sắt, đồng, iot… giảm nguy cơ mắc bệnh sỏi thận, giảm lượng calo dư thừa.', '/fruits/Cam/Quýt Úc/quytuc.jpg', 2019, 2020),
(11, 'ND2', 'Nho Autumn Crisp', 'Úc', 17, 'Nho', 259000, 0, '</strong>1.  Giới thiệu</strong>\r\nNho xanh Autumn Crisp Úc được thu hoạch từ đầu tháng 10 đến cuối tháng 12. Tuy nhiên, với công nghệ bảo quản lạnh với nhiệt độ nghiêm ngặt, nho có thể giữ được độ tươi ngon đến tận tháng 5, tháng 6 năm sau.\r\nTác dụng nổi bật của nho Autumn Crisp Úc: \r\n- Kiểm soát lương đường trong máu\r\n- Tăng cường khả năng tập trung, cải thiện trí nhớ\r\n- Tốt cho hệ tim mạch\r\n- Cải thiên chứng táo bón\r\n- Ngăn ngừa các tác nhân gây ung thư\r\n\r\n\r\n<img src=\"/fruits/content/nhoautu1.png\">\r\n\r\n\r\n\r\n</strong>2.  Đặc điểm</strong>\r\nNho xanh không hạt Úc thịt giòn, ngọt, vỏ mỏng. Quả nho tròn, căng mọng nước. Bên ngoài mỗi quả nho được bao bọc bởi một lớp phấn tự nhiên mỏng giúp bảo vệ quả trong suốt quá trình từ khi phát triển đến tay khách hàng.\r\n\r\n</strong>3.  Dinh dưỡng và sức khỏe</strong>\r\nNho xanh là loại quả có rất nhiều chất dinh dưỡng mang lại sức khỏe và tinh thần cho người sử dụng:\r\n-   Có tác dụng bổ tỳ, ích khí, giúp cơ thể khỏe mạnh, miễn dịch tốt\r\n-   Canxi, kali, photpho, sắt, vitamin B1, B2, B6, C cùng các loại axit amin cần thiết là một thần dược cho người suy nhược thần kinh, mệt mỏi quá sức\r\n -   Resvartion là hợp chất chống oxy hóa cao gấp 7 lần so với cac loại vitamin E thông thường, là thực phẩm bổ dưỡng cho phụ nữ, trẻ em và những người gầy yếu thiếu máu.\r\nNho có xuất xứ từ Chile còn bên cạnh loại đen không hạt còn có nho đỏ Chile và hiệu quả về sức khỏe nó mang lại cũng không kém.', '/fruits/Nho/Nho Autumn Crisp/nhoxanh.jpg', 2019, 2020),
(12, 'MA1', 'Mận Úc', 'Úc', 24, 'Mận', 71000, 0, '<strong>1. Giới thiệu</strong>\r\nMận đường Úc là một đa dạng độc đáo của mận. Trong khi mận thường tròn và gần như là lớn như một quả táo hoặc cam, mận đường có một hình dạng bầu dục,  lớn hơn ngón tay cái của người bình thường một chút. Mận đường là một sự lựa chọn ăn vặt tốt của bạn, chúng ta có thể bỏ chúng vào miệng và ăn một cách dễ dàng, vừa miệng. Như  cái tên của nó cho thấy  mận này vị ngọt, ngon.\r\n\r\n\r\n<img src=\"/fruits/content/manucc1.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm</strong>\r\nMận đường chưa đến độ chín sẽ có màu xanh hơi ngả vàng. Lúc này mận sẽ giòn hơn và lưu trữ được lâu hơn, không nhanh bị mềm. Mận đường khi chín có màu tím đỏ sẫm, có một lớp phủ bụi trắng gọi là \"sáp nở\" hay lớp sáp phấn. Sáp nở là cơ chế phòng thủ tự nhiên của trái cây chống lại sâu bệnh và môi trường và đây cũng là cách khôn ngoan để chúng ta nhận biết xem các loại trái cây mà lớp sáp vẫn còn nguyên vẹn thì rất tươi ngon.\r\n\r\n<strong>3. Giá trị dinh dưỡng</strong>\r\nMận Úc nhập khẩu được quảng cáo là giàu chất oxi hóa, vitamin C, A,…và các vi chất dinh dưỡng như K, Mn, Đồng… và có tác dụng giải nhiệt, hỗ trợ hệ tiêu hóa.', '/fruits/Mận/Mận Úc/man.jpg', 2019, 2020),
(13, 'MA2', 'Mận October Sun', 'Mỹ', 45, 'Mận', 123000, 0, '<strong>1. Giới thiệu</strong>\r\nMận October Sun mỹ là loại cây thích hợp với khí hậu khô, nóng vì thế được trồng rất phổ biến ở thung lũng Mississippi và miền nam nước Mỹ. Bởi ngoài khí hậu thuận lợi, ở đây còn có hệ thống tưới tiêu tốt luôn cung cấp đầy đủ nước cho mận phát triển.\r\nBạn dễ dàng mua được Otober sun tại các cửa hàng  trái cây nhập khẩu tại Việt Nam từ thấng 7 đến tháng 10 hàng năm.\r\n\r\n\r\n<img src=\"/fruits/content/manoct1.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm</strong>\r\nMận October Sun có hình dáng tròn, màu xanh ngọc đẹp mắt, rãnh nhỏ, vỏ có một lớp phấn tắng tự nhiên bảo vệ quả. Mỗi quả trung bình đạt từ 90g đến 120g.\r\nVị của October sun ngọt sắc, khi cắn bạn sẽ cảm nhận ngay vị giòn mọng nước thấm dần trên đầu lưỡi thật sự sảng khoái. \r\n\r\n<strong>3. Giá trị dinh dưỡng</strong>\r\nMận October sun mỹ là một thực phẩm độc đáo chứa nhiều dinh dưỡng tốt cho sức khỏe của con người.\r\n-   Acid neochlorogenic và chlorogenic trong mận có tác dụng giảm nguy cơ, phòng tránh các bệnh cơ vữa động mạch, bệnh tim\r\n-   26% trong mận là vitamin C, giúp các mô và hệ thống miễn dịch luôn khỏe mạnh\r\n-   Axit citric giúp hấp thụ vitamin và các enzyme giảm căng thẳng mệt mỏi và khôi phục lại năng lượng.\r\n-   Axit malic có trong quả  mận là thành phần có khả năng chống táo bón và các tác động xấu của thực phẩm khi vào trong ruột.\r\n', '/fruits/Mận/Mận October Sun/manvang.jpg', 2019, 2020),
(14, 'ND3', 'Nho Đen', 'Mỹ', 22, 'Nho', 139000, 0, '<strong>1.   Giới thiệu</strong>\r\nNho đen không hạt Mỹ có xuất xứ từ bang California, Oregon, Washington những nơi có khí hậu ấm áp và khô. Với đa dạng các chủng: Autumn royal, Midnight Beauty, Sugrathirteen, Summer Roya và loại Autumn royal là loại ngon hơn hẳn.\r\nNho đen không hạt Mỹ đã chinh phục và được ưa thích trên toàn thế giới. ở Việt Nam, tại các cửa hàng  hoa quả nhập khẩu bạn sẽ dễ dàng bắt gặp nó vào khoảng từ tháng 5 đến tháng 1 năm sau.\r\n\r\n\r\n<img src=\"/fruits/content/nhoden1my.jpg\">\r\n\r\n\r\n<strong>2.  Đặc điểm</strong>\r\nNho đen không hạt có hình tròn thon, màu đen sẫm, vỏ mỏng. Ăn rất ngọt nhưng vẫn có vị thanh mát, đặc biệt là không hạt.\r\nNhững đặc tính là cũng là cách để người tiêu dùng biết cách phân biệt với các sản phẩm nho độc hại của Trung Quốc.\r\n\r\n<strong>3.  Dinh dưỡng và sức khỏe</strong>\r\nNho đen là loại hoa quả rất giàu dinh dưỡng, có tác dụng bổ tì, ích khí, giúp cơ thể khỏe mạnh, miễn dịch tốt và làm chậm quá trình lão hóa\r\n-    Canxi, kali, photpho, sắt, vitamin B1, B2, B6, C và các loại axit amin cần thiết tốt cho người suy nhược thần kinh và có lợi cho tiêu hóa\r\n-    Hợp chất Resveratrol trong nho đen không thịt mỹ đặc biệt là phần vỏ giúp giải độc tốt, giảm máu nhiễm mỡ, chống tụ huyết, phòng chống xơ vỡ động mạch và tăng cường hệ thống miễn dịch của cơ thể', '/fruits/Nho/Nho Đen/nhodenMy.jpg', 2019, 2020),
(15, 'CR1', 'Cherry', 'Mỹ', 32, 'Cherry', 333000, 0, '<strong>1. Đặc điểm</strong>\r\nCherry Mỹ đầu vụ, cành cuống xanh tươi, quả đanh chắc. Vị ngọt xen một chút vị chua dịu của trái đầu mùa.\r\nQuả cherry rất tốt cho những người bị cao huyết áp. Đây cũng là một trong những loại quả giúp bạn loại bỏ được mức độ cholesterol xấu trong cơ thể.\r\n\r\n\r\n<img src=\"/fruits/content/cherrymy1.jpg\">\r\n\r\n\r\n<strong>2. Giá trị dinh dưỡng</strong>\r\nNếu bạn ăn cherry thường xuyên, tình trạng mất ngủ của bạn sẽ được cải thiện. Cherry chứa melatonin làm cho giấc ngủ sâu và ngon hơn. Do đó, thay vì uống thuốc an thần, bạn hãy ăn vài quả anh đào mỗi ngày để cải thiện giấc ngủ chất lượng hơn.\r\nCherry là thực phẩm tốt cho não bộ, tăng trí nhớ bởi chúng chứa các chất chống ôxy hóa anthocyanin. Vì vậy, nếu bạn đang cảm thấy thỉnh thoảng mình hat quên vặt, quả anh đào có thể giúp khắc phục giảm khả năng mất trí nhớ.\r\nBên cạnh đó, cherry rất tốt cho mắt. Hàm lượng vitamin A có trong cherry nhiều hơn khoảng 20 lần so với dâu tây hay việt quất. Cherry chứa nhiều vitamin A và một phần của vitamin này là beta carotene giúp thúc đẩy tầm nhìn tốt và giữ cho đôi mắt của bạn khỏe mạnh.\r\nĂn cherry thường xuyên có thể phòng ngừa ung thư bởi chúng chứa chất chống ôxy hóa có tác dụng ngăn chặn các gốc tự do gây tổn thương tế bào và mô, làm giảm nguy cơ ung thư và chậm quá trình lão hóa.\r\nBên cạnh đó, loại quả này được chứng minh làm giảm nguy cơ bệnh tim và rất tốt cho sức khỏe tổng thể.\r\nMột tác dụng lớn của cherry đó là có thể giúp giảm đau, sưng đối với các bệnh mạn tính, bao gồm cả gút và viêm khớp. Nếu bạn bị đau khớp, hãy cố gắng ăn một ít cherry mỗi ngày thay vì uống thuốc. Loại trái này cũng được chứng minh giúp bạn giảm đau bụng khi có nguyệt san.\r\nVới những người bị tiểu đường, quả cherry rất hữu dụng. Trái cây này giúp giảm nguy cơ mắc bệnh tiểu đường bởi chất anthocyanin làm tăng khả năng sản sinh insulin. Bệnh nhân có thể chọn quả anh đào như một bữa ăn nhẹ.Cuối cùng, tác dụng quan trọng không thể nhắc đến đó là, cherry có khả năng kháng viêm mạnh mẽ. Những bệnh nhân bị viêm khớp hay các vận động viên nếu uống nước trái cây cherry pha loãng 3 lần/ngày, tình trạng sức khỏe sẽ được cải thiện.', '/fruits/Cherry/Cherry/cherrymy.jpg', 2019, 2020),
(16, 'TA1', 'Táo Envy', 'Mỹ', 45, 'Táo', 62000, 0, '<strong>1.  Giới thiệu</strong>\r\nLà kết quả của quá trình lai tạo giữa Braeburn và Royal Gala, Envy được nghiên cứu và thử nghiệm trong vòng 25 năm (từ 1960 đến 1985) mới có được kết quả tuyệt vời như ngày nay.\r\nMùa vụ của Envy bắt đầu từ tháng 2 đến hết tháng 10 hàng năm, nhờ công nghệ bảo quản hiện đại hoàn toàn bằng nhiệt độ lạnh (CA của Mỹ), táo có thể giữ nguyên được chất lượng trong thời gian dài và bán quanh năm tại các cửa hàng hoa quả sạch.\r\n\r\n\r\n<img src=\"/fruits/content/taoenvy1.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm</strong>\r\nTáo Envy có các sọc màu đỏ ruby ở vỏ với màu xanh lá cây nhạt ở gần cuống . Thịt của Envy rất sắc nét, thịt trắng ngọt ngào và trong điều kiện tốt nó có thể giữ được độ trắng của thớ thịt lên tới 10h (thực tế Luôn Tươi Sạch thử tại các cửa hàng là hơn 2h).\r\nSize nhỏ có kích thước khoảng 5 quả/kg, thịt giòn đanh, nhiều nước, vị ngọt đậm và rất thơm. Là trái cây cao cấp không chỉ có mặt trong thực đơn hàng ngày của các gia đình mà Envy còn được chọn làm quà biếu, quà tặng. \r\n\r\n<strong>3.   Giá trị dinh dưỡng</strong>\r\n-    Trong một quả  táo Envy chứa lượng lớn kẽm, rất quan trọng với cơ thể giúp làm tăng khả năng ghi nhớ của người. Ngoài ra, kẽm còn kết hợp với một số chất khác trong cơ thể để nâng cao sức đề kháng của cơ thể.\r\n-    Táo envy cũng chứa nhiều vitamin và khoáng chất khác như canxi, kali, sắt, phốt pho, Vitamin B1, B2, C; có khả năng tăng cường hệ miễn dịch, tạo ra nhiều máu đỏ, tốt cho hệ thần kinh,...\r\n-    Là quả chứa nhiều chất xơ nên rất có lợi cho đường tiêu hóa, là một loái trái cây phù hợp cho trẻ nhỏ và người lớn tuổi.', '/fruits/Táo/Táo Envy/taoenvy.jpg', 2019, 2020),
(17, 'TA2', 'Táo Ambrosia', 'Mỹ', 36, 'Táo', 120000, 0, '<strong>1. Giới thiệu</strong>\r\nTáo Ambrosia có nguồn gốc từ Columbia trong những năm 1990, được phát hiện ra từ một cây con bởi nhà Mennel từ British Columbia. Hiện nay, cây được nhân giống và trồng nhiều ở Mỹ, Châu Âu, Chile và New Zealand. Đây đều là những nơi có khí hậu mát mẻ về đêm và nắng ấm ban ngày nên rất thích hợp để cho táo phát triển đạt chất lượng tốt nhất.\r\nMùa thu hoạch từ tháng 2 đến tháng 8 hàng năm. Nhờ công nghệ bảo quản CA của Mỹ mà táo có thể giữ được độ tươi ngon đến 6 tháng. Hầu như Ambrosia được bán quanh năm và đặc biệt được người tiêu dùng Việt Nam tin tưởng sử dụng trong một thời gian dài.\r\n\r\n\r\n<img src=\"/fruits/content/a.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm</strong>\r\nTáo Ambrosia quả to, vỏ mỏng, thịt giòn ngọt mát. Vỏ ngoài có màu vàng kem xen lẫn màu đỏ đậm rất bắt mắt.\r\n\r\n<strong>3. Giá trị dinh dưỡng</strong>\r\nTáo cung cấp chất xơ rất tốt , giúp ổn định lượng đường trong máu, giúp bộ máy tiêu hóa hoạt động tốt. Lượng đường tự nhiên trong táo không làm ảnh hưởng đến bệnh nhân tiểu đường.\r\nTáo Ambrosia có hàm lượng axit thấp, là một lựa chon tốt cho trẻ em và người già vì dễ tiêu hoa.\r\nGiống nhiều loại táo khác, táo Ambrosia chứa nhiều chất pectin, đồng thời cũng có nhiều chất xơ hòa tan làm giảm Cholestorol và chất chống oxi hóa. Đây là hai chất rất tốt cho việc phòng ngừa bệnh tim mạch.\r\nHàm lượng vitamin C và A cao hỗ trợ tăng cường hệ miễn dịch cho cơ thể, kích thích ăn ngon và đồng thời tiêu diệt các gốc tự do gây ra bệnh tuổi già hay lão hóa.\r\n', '/fruits/Táo/Táo Ambrosia/taoambro.jpg', 2019, 2020),
(18, 'TA3', 'Táo Granny Smith', 'Mỹ', 32, 'Táo', 75000, 0, '<strong>1.  Giới thiệu</strong>\r\nTáo Granny Smith có nguồn gốc từ trang trại ở Eastwood, New South Wasles, Úc năm 1868 và chính thức được công bố ra thị trường năm 1924. Táo xanh du nhập và được trồng thương mại tại Mỹ bắt đầu từ cuối năm 1960.\r\nCùng với Red Delicious, Fuji, Ambrosia,… thì táo xanh Granny Smith là một trong những giống táo được trồng phổ biến nhất ở tiểu bang Washington của Mỹ. Đây là vùng đất màu mỡ với khí hậu khô nóng quanh năm nên ít côn trùng và dịch bệnh, hệ thống tưới tiêu thuận lợi do sông Columbia và vùng núi Cascade cung cấp nên rất thuận lợi cho việc trồng táo\r\nTáo Xanh Mỹ có vụ mùa bắt đầu từ tháng 10 hàng năm, với công nghệ bảo quản hiện đại, an toàn CA táo có thể giữ được độ tươi ngon trong vòng nhiều tháng. Nhờ đó bạn có thể mua được táo xanh quanh năm tại các cửa hàng hoa quả nhập khẩu, siêu thị trên toàn thế giới.\r\n\r\n<img src=\"/fruits/content/taogr.jpg\">\r\n\r\n\r\n<strong>2.  Đặc điểm</strong>\r\nQuả nhỏ, trung bình khoảng 5 – 6 quả/kg, vỏ ngoài phớt màu hồng nhẹ trên nền xanh lá cây mát mắt. Thịt có màu trắng sáng và không bị chuyển màu nâu khi để ở nhiệt độ môi trường, thịt giòn vừa phải, có vị rôn rốt rất đặc trưng.\r\nThích hợp làm salad, ép nước hoặc nguyên liệu cho món bánh trái cây giàu dinh dưỡng.\r\n\r\n<strong>3.  Giá trị sức khỏe</strong>\r\nTáo xanh Mỹ là một trong những thực phẩm tốt nhất cho sức khỏe tổng thể và sắc đẹp mà bạn nên biết và nên ăn hàng ngày:\r\n-   Trong một quả táo có chứa khoảng 4g chất xơ, đáp ứng được 17% nhu cầu cần thiết của cơ thể mỗi ngày. Giúp điều trị bệnh tiểu đường, cải thiện chức năng của hệ tiêu hóa,bảo vệ tim mạch, hỗ trợ giảm cân hiệu quả\r\n-   Lượng vitamin A, C, B1 dồi dào tăng cường sức khỏe, chống lại các gốc tự do, ngăn ngừa ung thư và làm chậm quá trình lão hóa\r\n-   Hàm lượng khoáng chất: kali, canxi, photpho, sắt,… dồi dào tốt cho da, tóc, móng; giảm triệu chứng của các bệnh về xương khớp.\r\n\r\n\r\n', '/fruits/Táo/Táo Granny Smith/taoxanh.jpg', 2019, 2020),
(19, 'ND4', 'Nho Ninh Thuận', 'Việt Nam', 20, 'Nho', 80000, 0, '<strong>Nho xanh Ninh Thuận</strong> là một trong những đặc sản nổi tiếng nhất của vùng đất nắng gió này. Nho xanh Ninh Thuận có màu xanh ngả vàng nhạt, vỏ dày, hình oval to khoảng đầu ngón tay cái, với vị ngọt đậm không gắt, chua rất nhẹ, và có hạt đặc trưng của Nho Ninh Thuận.\r\n\r\n<img src=\"/fruits/content/nxnt.jpg\">\r\n\r\n<strong>Nho xanh Ninh Thuận</strong> hiện nay rất được các khách hàng ưa chuộng.\r\nVietropfruit tự hàng mang đến cho quý khách hàng sản phẩm nho xanh Ninh Thuận được thu hoạch trực tiếp tại vườn nho Phan Rang, đảm bảo chất lượng và an toàn nhất.', '/fruits/Nho/Nho Ninh Thuận/nhoxanhnt.jpg', 2019, 2020),
(20, 'TA4', 'Táo Ninh Thuận', 'Việt Nam', 30, 'Táo', 40000, 0, '<strong>Táo xanh Ninh Thuận</strong> là loại táo sạch được trồng tại Ninh Thuận, có vị ngọt tự nhiên, không gắt, ăn rất giòn.\r\nĐặc biệt, <strong>Táo xanh Ninh Thuận</strong> không sử dụng chất bảo quản nên rất an toàn cho người dùng.\r\n\r\n\r\n<img src=\"/fruits/content/txnt1.jpg\">\r\n\r\n\r\n<strong>Táo xanh Ninh Thuận</strong> có hàm lượng dinh dưỡng cao, đặc biệt là hàm lượng vitamin C cao gấp 10 lần so với cam quýt. Vì vậy, táo có tác dụng tuyệt vời trong việc tăng cường sức đề kháng, chống oxy hóa, rất tốt cho sức khỏe cũng như làn da của chị em phụ nữ.\r\n\r\n\r\n\r\n', '/fruits/Táo/Táo Ninh Thuận/taoxanhninhthuan.png', 2019, 2020),
(21, 'XO1', 'Xoài Cát', 'Việt Nam', 30, 'Xoài', 45000, 0, '<strong>Xoài Cát chu Cao Lãnh Đồng Tháp</strong> là giống xoài truyền thổng của địa phương có từ rất lâu đời. Tương truyền, ngày xưa vua Gia Long lánh nạn ở Nha Mân, rất thích dùng xoài Cao Lãnh. Người đẹp Nha Mân vốn gốc là cung tần, phi nữ của Gia Long, còn giống xoài thì được tôn xưng là xoài ngự vì tốt mã lại thơm ngon\r\n\r\nXoài cát Cao Lãnh Đồng Tháp có trọng lượng trung bình 350-450g, hình thon dài, khi chín vỏ màu vàng nhạt. Thịt xoài Cát Chu ít xơ, mềm mà hơi dai, lại rất ngọt và thơm. Khi ăn miếng xoài tan nhẹ trong miệng và vị ngọt dịu vẫn còn đọng mãi trên đầu lưỡi. Xoài này giàu lượng acid amin rất cần thiết cho cơ thể.\r\n\r\n<img src=\"/fruits/content/xcdt.jpg\">\r\n\r\n\r\nTrong 100g xoài chín có 15.9g glucid, 0.6g protein, 0.3g lipid, 10mg canxi, 0.3mg sắt, 1880microgam Vitamin A, 0.06 mg vitamin B1, 36 Vitamin C … và nhiều sinh tố vi lượng có ích khác. Cung cấp 62 calo, 78% nhu cầu vitamin A mỗi ngày, rất tốt cho sự phát triển của trẻ em, làn da và thị lực; 46% nhu cầu Vitamin C. Quả xoài xanh thái mỏng, phơi khô hoặc sấy khô là nguồn vitamin C thiên nhiên dồi dào. Xoài chín có tác dụng bổ não, có lợi cho người làm việc trí óc, suy nhược thần kinh.', '/fruits/Xoài/Xoài Cát/xoaicat.png', 2019, 2020),
(22, 'ND5', 'Nho Đỏ', 'Mỹ', 29, 'Nho', 100000, 0, '<strong>1. Giới thiệu</strong>\r\nNho đỏ không hạt Mỹ được phát triển bởi một chương trình nhân giống ở Fresno, California vào những năm 1970. Các chủng Nho đỏ phổ biến gồm có:  Crimson (T8- T1) , Flame (T5- T12), Ruby (T8- T1) , Sunser, Scartlet Royal (T10 – T1), Sugrathnineteen.\r\n\r\n\r\n<img src=\"/fruits/content/nhodo1.jpg\">\r\n\r\n\r\n<strong>2. Đặc điểm</strong>\r\nĐặc điểm của nho đỏ không hạt Mỹ quả màu đỏ tươi, tròn hoặc thuôn dài, vỏ mỏng, vị ngọt, không hạt.\r\n\r\n<strong>3. Giá trị dinh dưỡng</strong>\r\nNho đỏ có thể giảm nguy cơ tai biến tim mạch, giảm tác hại của thuốc lá đối với phổi, ngăn ngừa ung thư và giúp cơ thể chống đỡ tốt hơn những tác dụng phụ mà việc điều trị ung thư gây ra, rất phù hợp làm quà biếu phụ nữ, trẻ em.\r\nHợp chất resveratrol trong lớp vỏ của nho đỏ (nho xanh không có chất này) có tác dụng ngăn hồng cầu kết dính vào nhau, làm giảm nguy cơ hình thành các cục máu đông, tăng cholesterol tốt (HDL) và giảm cholesterol xấu (LDL). Resveratrol có khả năng chống oxy hóa mạnh gấp 7 lần vitamin E.\r\nNước ép từ quả nho đỏ có khả năng ngăn ngừa ung thư và tăng cường sức chống đỡ của cơ thể trước những tác hại của hóa trị và xạ trị. Một nghiên cứu khác cho thấy, nước ép nho đỏ có hoạt tính chống oxy hóa mạnh gấp 3 lần so với nước ép cà chua, cam, bưởi.', '/fruits/Nho/Nho Đỏ/nhodomy.png', 2019, 2020),
(23, 'DU1', 'Dứa-Thơm', 'Việt Nam', 42, 'Dứa', 55000, 0, '<strong>Quả dứa</strong> (trái thơm) dùng làm thức uống giải nhiệt ngày nóng nực rất tốt. Nó còn dùng để chữa một số bệnh.\r\n\r\nQuả dứa hay còn gọi là trái thơm, khóm… có nhiều loại khác nhau.\r\n\r\nQuả dứa thực ra là trục của bông hoa và các lá bắc mọng nước tụ hợp lại. Còn trái thật là các “mắt thơm”.\r\nTrong 100g quả dứa, phần ăn được cho Ĳ5kcal, 0,03mg caroten, 0,08mg vitamin B1, 0,02mg vitamin B2, 16mg vitamin C (thơm tây). Các chất khoáng là 16mg Ca, 11mg phospho, 0,3mg Fe, 0,07mg Cu, 0,4g protein, 0,2g lipid, 13,7g hydrat cacbon, 85,3g nước, 0,4g xơ.\r\n\r\nTrong quả dứš có chứa enzyme bromelin hay bromelain, có thể phân hủy protein. Do vậy, quả dứa được sử dụng trong chế biến một số món ăn như: thịt bò xào, thịt vịt xào để giúp thịt nhanh mềm và tạo hương vị đặc trưng. Trong dân gian thường ướp các loại thịt dai, già với dứa hoặc xào cùng thịt, thịt sẽ được nhừ, ăn dễ tiêu.\r\n\r\n<img src=\"/fruits/content/quadua.jpg\">\r\n\r\n\r\nMỗi ngày uống một cốc nước ép quả dứa hoặc ăn 1/2 quả dứa chín có thể thay thế được các loại thuốc chống đông\r\nCác nghiên cứu vào các năm 1960 – 1970 đã xác định bromelin của quả dứa có đặc tính kháng phù và kháng viêm. Từ đó, vài công ty dược đã đưa ra các thực phẩm bổ sung có chứa chất chiết từ quả dứa để giải quyết viêm mô tế bào, làm tan các cục mỡ nổi cộm. Tuy nhiên, chưa có nghiên cứu nào xác định dứa có khả năng làm tan các khối mỡ không đẹp này. Bromelin giảm thiểu viêm xoang. Ở Đức, trẻ em bị viêmĠxoang thường được chữa trị bằng bromelin, chiết xuất từ trái thơm. Bromelin cho kết quả tốt, nó làm giảm thời gian bị bệnh (từ 8 ngày, còn 6 ngày). Bromelin dùng làm thuốc tẩy giun như một loại giun nhỏ, thường gặp ở trẻ em. Qua nghiên cứu của HordegenĠP., bromelin cũng cho thấy kết quả tốt như Pyratel.\r\n\r\nQuả dứa làm liền sẹo, một số enzyme của quả dứa làm mau lành các vết thương ở da hay các vết phỏng như chuột bị phỏng, khi dùng chất chiết xuất từ quả dứa giúp tiến trình làm sạchĠmột vết thương sau 4 giờ, lấy đi các vật lạ và mô chết để không còn trở ngại nào cho vết thương lành lại. Bromelin còn làm giảm hiện tượng phù nề, các vết bầm tím trên da và giảm đau nhức.', '/fruits/Dứa/Dứa-Thơm/duathomm.jpg', 2019, 2020);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(20) NOT NULL,
  `password` varchar(20) NOT NULL,
  `fullname` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `admin` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `password`, `fullname`, `email`, `phone`, `admin`) VALUES
(1, 'admin', 'admin', 'Cuong', 'nguyencuong@gmail.com', '0987654321', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fruit`
--
ALTER TABLE `fruit`
  ADD PRIMARY KEY (`fruit_id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`,`username`,`email`,`phone`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fruit`
--
ALTER TABLE `fruit`
  MODIFY `fruit_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
